### PR TITLE
Poll for new status after update 

### PR DESCRIPTION
**Pull request by natefox**
Fixes https://github.com/home-assistant/core/issues/117052

See https://github.com/home-assistant/core/issues/117052#issuecomment-2274338036 for more detail

### CODE REVIEW

**Comment by warmfire540** [comment]
@natefox how reliable is this 100ms delay?  will sometimes it be 120ms needed, etc?

if we know we are disabling, could we poll until it is actually disabled?  maybe someone has a slow network or slow pi-hole

**Comment by natefox** [comment]
As I've been reading piholes code, it looks like the delay is just from the
signal to FTLDNS to reload it's config. I've come around to agreeing that
polling is the right thing to do.

On vacation this week, will update my PR if someone doesn't beat me to it.
I'll also probably submit an enhancement PR to pihole to negate this need
but we'd still need to support these non-enhanhanced versions anyway.

**Comment by natefox** [comment]
Finally got around to updating this. Opted to keep the polling within the original `timeout(5)` rather than add another timeout just for the polling. I'm open to adjusting though.

**Comment by Jab2870** [comment]
so, just wanted to give feedback and say that this patch is working and has been working fine for me for a while. Is there any specific tests anyone would like me to do that might help get it merged?

**Pull request merged**
